mobile friendly mods
DavidSouther/computron5k pull request #7
Opened 2022-05-27 02:36 UTC by LateBy5

Updated the memory component and cpu page to be slightly more mobile friendly. Tested various viewports out locally - changes look alright.

2022-05-28 23:45 UTC, DavidSouther requested changes

2022-05-28 23:45 UTC, DavidSouther commented on src/pages/cpu.ts
> +            gridColumn: "3 / span 4",
It looks like this can be 3 / span 2

2022-05-28 23:45 UTC, DavidSouther commented on src/pages/cpu.ts
>          "@media (max-width: 1195px)": {
I know you found it this way, but this is backwards - we want to only use the min-width media selectors, inline with the breakpoints in picocss.

2022-05-28 23:45 UTC, DavidSouther commented on src/pages/cpu.ts
> +            width: "100%",
This width turns out we don't need

2022-05-28 23:45 UTC, DavidSouther commented on src/components/screen.ts
> +          marginInline: "auto",
marginInline is the secret sauce, here, and we can remove the width to keep the border tight around the canvas

2022-05-29 07:07 UTC, LateBy5 commented on src/pages/cpu.ts
>          "@media (max-width: 1195px)": {
Our version of pico css doesn't seem to contain media queries for the container class, so I shimmed them in the js for the time being

2022-05-29 07:08 UTC, LateBy5 commented on src/components/screen.ts
> +          marginInline: "auto",
> marginInline is the secret sauce, here, and we can remove the width to keep the border tight around the canvas

Turns out we don't need either. Instead I'm using text-align to center the canvas within the figure element - that way nothing gets screwy with the horizontal scrolling

2022-05-29 07:09 UTC, LateBy5 commented
Per your initial comments, I took a first look at pico css (lol - should of did that from the start). I updated the styling to use / align with the ethos of pico css

2022-05-30 21:49 UTC, DavidSouther commented on src/pages/cpu.ts
>          "@media (max-width: 1195px)": {
We could add containers using the query params to pico, but this is I think better without them.

2022-05-30 21:49 UTC, DavidSouther commented on src/components/screen.ts
> +          marginInline: "auto",
Great - and then, the last piece is the border stays visible but doesn't get wider than the canvas.

2022-05-30 22:00 UTC, DavidSouther approved these changes

2022-05-30 22:00 UTC, merged